# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ARTranslator' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ARTranslator
	pod 'Firebase/MLNLLanguageID'
	pod 'Firebase/MLNLTranslate'
	pod 'Firebase/MLVisionTextModel'
	pod 'Firebase/MLVision'
  target 'ARTranslatorTests' do
    inherit! :search_paths
    # Pods for testing
    
  end

end
